"""Field limits for models of 'Level_Tests' application."""

FIELD_LIMITS_LEVEL_TESTS_APP = {
    "LEVEL_TEST_NAME_MAX_CHAR": 100,
    "QUESTION_NAME_MAX_CHAR": 350,
    "QUESTION_EXPLANATION_MAX_CHAR": 550,
    "QUESTION_NUMBER_MIN_VALUE": 1,
    "QUESTION_NUMBER_MAX_VALUE": 100,
    "ANSWER_NAME_MAX_CHAR": 350,
    "ANSWER_NUMBER_MIN_VALUE": 1,
    "ANSWER_NUMBER_MAX_VALUE": 5,
    "LEVEL_TEST_PROGRESS_MIN_ANSWERS": 0,
    "LEVEL_TEST_PROGRESS_MAX_ANSWERS": 100,
}
