volumes:
  pg_data:
  pg_admin:

networks:
  postgres:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../backend/development_tracker/.env
    networks:
      - postgres
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ../backend/development_tracker/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DISABLE_POSTFIX: 'True'
    volumes:
       - pg_admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: on-failure
