# Generated by Django 4.2.2 on 2023-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "An article with this name already exists."
                        },
                        help_text="Article's name",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        error_messages={
                            "unique": "An article with this url already exists."
                        },
                        help_text="Article's url",
                        max_length=300,
                        unique=True,
                        verbose_name="url",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        help_text="Article's skills",
                        related_name="articles",
                        to="skills.skill",
                        verbose_name="skills",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
    ]
