# Generated by Django 4.2.2 on 2023-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "A course with this name already exists."
                        },
                        help_text="Course's name",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        error_messages={
                            "unique": "A course with this description already exists."
                        },
                        help_text="Course's description",
                        max_length=700,
                        unique=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        help_text="Course's skills",
                        related_name="courses",
                        to="skills.skill",
                        verbose_name="skills",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
    ]
