# Generated by Django 4.2.2 on 2023-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paid_courses",
            field=models.ManyToManyField(
                help_text="User's paid courses",
                related_name="users",
                to="courses.course",
                verbose_name="paid courses",
            ),
        ),
    ]
