# Generated by Django 4.2.7 on 2023-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_paid_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with this email already exists."},
                help_text="User's email address",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
