# Generated by Django 4.2.7 on 2023-11-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillprogress",
            name="skill",
            field=models.ForeignKey(
                help_text="Skill",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill_progresses",
                to="skills.skill",
                verbose_name="skill",
            ),
        ),
    ]
