# Generated by Django 4.2.2 on 2023-11-28 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "A goal with this name already exists."
                        },
                        help_text="Skill's name",
                        max_length=150,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Level",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="level",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="goal completion date",
                        null=True,
                        verbose_name="deadline",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        help_text="Goals skills",
                        related_name="goals",
                        to="skills.skill",
                        verbose_name="skills",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "goal",
                "verbose_name_plural": "goals",
            },
        ),
    ]
