# Generated by Django 4.2.7 on 2023-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="name",
            field=models.CharField(
                help_text="Skill's name", max_length=150, verbose_name="name"
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_name_user_goal"
            ),
        ),
    ]
