# Generated by Django 4.2.2 on 2023-11-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articles",
                    models.ManyToManyField(
                        help_text="Reccomendation's articles",
                        related_name="recommendations",
                        to="articles.article",
                        verbose_name="articles",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        help_text="Reccomendation's courses",
                        related_name="recommendations",
                        to="courses.course",
                        verbose_name="courses",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "recommendation",
                "verbose_name_plural": "recommendations",
            },
        ),
    ]
