# Generated by Django 4.2.7 on 2023-11-30 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0002_alter_skillprogress_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Answer to the question",
                        max_length=350,
                        verbose_name="answer text",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates the answer is correct",
                        verbose_name="is answer correct",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Number of this answer in the test questions",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="answer number for order in test questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        help_text="Answer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="level_tests.answer",
                        verbose_name="answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "choice",
                "verbose_name_plural": "choices",
                "ordering": ("user",),
            },
        ),
        migrations.CreateModel(
            name="LevelTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "unique": "A level test with this name already exists."
                        },
                        help_text="Name of the level test",
                        max_length=100,
                        unique=True,
                        verbose_name="level test name",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill for test",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="level_test",
                        to="skills.skill",
                        verbose_name="skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "level test",
                "verbose_name_plural": "level tests",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Text of the question",
                        max_length=350,
                        verbose_name="question text",
                    ),
                ),
                (
                    "explanation",
                    models.CharField(
                        blank=True,
                        help_text="Text of the question explanation",
                        max_length=550,
                        verbose_name="question explanation",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Number of this question in the test",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="question number in test",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        help_text="Test",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="level_tests.leveltest",
                        verbose_name="test",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LevelTestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Count of correct answers in level test",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="count of correct answers in level test",
                    ),
                ),
                (
                    "wrong_answers",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Count of wrong answers in level test",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="count of wrong answers in level test",
                    ),
                ),
                (
                    "percentage_correct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="percentage of correct answers",
                        max_digits=4,
                        verbose_name="percentage of correct answers",
                    ),
                ),
                (
                    "choices",
                    models.ManyToManyField(
                        help_text="Choices",
                        related_name="level_test_progress",
                        to="level_tests.choice",
                        verbose_name="choices",
                    ),
                ),
                (
                    "level_test",
                    models.ForeignKey(
                        help_text="Level test",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="level_test_progress",
                        to="level_tests.leveltest",
                        verbose_name="level test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_test_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "level test progress",
                "verbose_name_plural": "level test progresses",
                "ordering": ("user",),
            },
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                help_text="Question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="level_tests.question",
                verbose_name="question",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="user",
            field=models.ForeignKey(
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="Question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="level_tests.question",
                verbose_name="question",
            ),
        ),
    ]
