# Generated by Django 4.2.7 on 2023-12-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_skill_description"),
        ("level_tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leveltest",
            name="skill",
            field=models.OneToOneField(
                help_text="Skill for test",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="level_test",
                to="skills.skill",
                verbose_name="skill",
            ),
        ),
    ]
