# Generated by Django 4.2.7 on 2023-12-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("level_tests", "0002_alter_leveltest_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="test",
            new_name="level_test",
        ),
        migrations.AddField(
            model_name="choice",
            name="level_test",
            field=models.ForeignKey(
                default=1,
                help_text="Level test for this choice",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="level_tests.leveltest",
                verbose_name="level_test",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("user", "level_test", "question"),
                name="unique_choice_test_user_question",
            ),
        ),
    ]
