# Generated by Django 4.2.7 on 2023-12-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "level_tests",
            "0003_rename_test_question_level_test_choice_level_test_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="level_test",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leveltestprogress",
            name="choices",
        ),
        migrations.AlterField(
            model_name="leveltestprogress",
            name="percentage_correct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="percentage of correct answers",
                max_digits=5,
                verbose_name="percentage of correct answers",
            ),
        ),
        migrations.AddConstraint(
            model_name="leveltestprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "level_test"), name="unique_progress_level_test_user"
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
