# Generated by Django 4.2.7 on 2023-12-07 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level_tests", "0004_remove_choice_answer_remove_choice_level_test_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leveltestprogress",
            name="percentage_correct",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="percentage of correct answers",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="percentage of correct answers",
            ),
        ),
    ]
